#!/bin/bash

bold="\e[1m"
reset="\e[0m"

echo -e "${bold}Hey $1..${reset}"
JAM=$(date "+%k")

if (( JAM < 6 ))
		then
			echo "It's too late, take some sleep!"
	elif (( JAM < 9 ))
		then
			echo "You're up early!"
	elif (( JAM < 12 ))
		then
			echo "Have a good day ahead!"
	elif (( JAM < 17 ))
		then
			echo "Good afternoon!"
	elif (( JAM < 20 ))
		then
			echo "Good evening!"
    else
			echo "It's time to wrap up for the day!"
fi
